### ISSUE TITLE
Android Version ?

### ISSUE THREAD

**Issue by fukhaos** [k0sukey/TiBubbleView#1]
Amazing module.
There is the possibility of a Android version ?

**Comment by k0sukey** [comment]
hmm, Android Java have Canvas like Objective-C CoreGraphics?
i'm try.

**Comment by k0sukey** [comment]
![2014-06-11 16 58 52](https://cloud.githubusercontent.com/assets/687233/3241542/5f9d5aca-f13e-11e3-8d3b-68761b0cf67c.png)
a littele more...

**Comment by fukhaos** [comment]
nice work !!

**Comment by yozef** [comment]
Nice :)

**Comment by k0sukey** [comment]
https://github.com/tdtsh/TiBubbleViewForAndroid

Android porting!
